
[colors]
background = '#1009078e'
black = '#100907'
blue = '#9B2407'
cursor = '#c3c1c1'
cyan = '#B72104'
foreground = '#c3c1c1'
green = '#CE1902'
magenta = '#E41E02'
red = '#D52303'
tabs = '#c3c1c1'
tabs-active = '#EA2603'
white = '#c3c1c1'
yellow = '#c3c1c1'
dim-black = '#1009078e'
dim-blue = '#9B24078e'
dim-cyan = '#B721048e'
dim-foreground = '#c3c1c18e'
dim-green = '#CE19028e'
dim-magenta = '#E41E028e'
dim-red = '#D523038e'
dim-white = '#EA26038e'
dim-yellow = '#c3c1c18e'
light-black = '#9B2407'
light-blue = '#B72104'
light-cyan = '#CE1902'
light-foreground = '#E41E02'
light-green = '#D52303'
light-magenta = '#EA2603'
light-red = '#c3c1c1'
light-white = '#9B2407'
light-yellow = '#B72104'
