#!/bin/bash

# Shell variables
# Generated by 'wal'
wallpaper="/home/aislx/.config/flames/wallpaper/dark-Testing/current.png"

# Special
background='#100907'
foreground='#c3c1c1'
cursor='#c3c1c1'

# Colors
color0='#100907'
color1='#9B2407'
color2='#B72104'
color3='#CE1902'
color4='#E41E02'
color5='#D52303'
color6='#EA2603'
color7='#c3c1c1'
color8='#695c56'
color9='#9B2407'
color10='#B72104'
color11='#CE1902'
color12='#E41E02'
color13='#D52303'
color14='#EA2603'
color15='#c3c1c1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
