name: Build AsiraOS ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pacman -Syu --noconfirm archiso git openssh curl

      - name: Build ISO
        run: |
          mkdir -p out work
          mkarchiso -v -w work -o out .

      - name: Add SSH key and trust SourceForge host
        env:
          SF_SSH_KEY: ${{ secrets.SF_SSH_KEY }}
        shell: bash
        run: |
          mkdir -p $HOME/.ssh
          echo "$SF_SSH_KEY" > $HOME/.ssh/id_ed25519
          chmod 600 $HOME/.ssh/id_ed25519
          ssh-keyscan frs.sourceforge.net >> $HOME/.ssh/known_hosts
          chmod 644 $HOME/.ssh/known_hosts

      - name: Upload to SourceForge with SSH
        env:
          SF_USER: ${{ secrets.SF_USER }}
          SF_PROJECT: ${{ secrets.SF_PROJECT }}
          SF_PATH: ${{ secrets.SF_PATH }}
        shell: bash
        run: |
          scp -i $HOME/.ssh/id_ed25519 -o UserKnownHostsFile=$HOME/.ssh/known_hosts out/* $SF_USER@frs.sourceforge.net:/home/frs/project/$SF_PROJECT/$SF_PATH/

      - name: Upload to AsiraOS Mirror (Official)
        shell: bash
        run: |
          # Ensure target folder exists
          chmod +x ./.github/scripts/upload-mirror.sh
          for file in ./out/*; do
            if [ -f "$file" ]; then
              echo "Uploading $file ..."
              ./.github/scripts/upload-mirror.sh upload "$file" AsiraOS-Beta
            fi
          done

      - name: Upload ISO as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: asiraos-release
          path: out/*.iso
