name: Build FlameOS ISO

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged   # mkarchiso needs this

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm archiso git

      - name: Build ISO
        run: |
          mkdir -p out work
          mkarchiso -v -w work -o out .

      - name: Upload ISO as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flameos-iso
          path: out/*.iso

      - name: Upload to SourceForge
        env:
          SF_USER: ${{ secrets.SF_USER }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_PROJECT: ${{ secrets.SF_PROJECT }}
          SF_PATH: ${{ secrets.SF_PATH }}
        run: |
          echo "$SF_PASSWORD" > sfpass.txt
          sshpass -f sfpass.txt scp -o StrictHostKeyChecking=no out/*.iso $SF_USER@frs.sourceforge.net:/home/frs/project/$SF_PROJECT/$SF_PATH/
          rm sfpass.txt
