name: Build FlameOS ISO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged   # mkarchiso needs this

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm archiso git

      - name: Build ISO
        run: |
          mkdir -p out work
          mkarchiso -v -w work -o out .

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: flameos-iso
          path: out/*.iso
