# .github/workflows/main.yml
name: Main
on: [workflow_dispatch]

jobs:
  upload-to-nextcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Archive files
        run: |
          sudo apt-get update
          sudo apt-get install zip wget -y
          mkdir -p out
          wget https://mirror.adectra.com/archlinux/iso/2025.09.01/archlinux-2025.09.01-x86_64.iso -O out/archlinux-2025.09.01-x86_64.iso

      - name: Upload to Next Cloud
        uses: Nghi-NV/next-cloud-upload-action@v1
        with:
          id: uploadFile
          filePath: "out/archlinux-2025.09.01-x86_64.iso"
          name: "documentation.zip"
          uploadPath: "aislx/FlameOS-Beta/"
          url: "cloud.theflames.fun"
          username: ${{ secrets.CLOUD_USERNAME }}
          password: ${{ secrets.CLOUD_PASSWORD }}
      - name: Get upload link
        run: |
          echo "${{ steps.uploadFile.outputs.output_url }}"
