name: Upload hello.txt to SourceForge with SSH Key

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: Install dependencies
        run: pacman -Syu --noconfirm openssh

      - name: Create hello.txt
        run: |
          mkdir -p out
          echo "Hello SourceForge!" > out/hello.txt

      - name: Set up SSH key
        env:
          SF_SSH_KEY: ${{ secrets.SF_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SF_SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts

      - name: Upload to SourceForge
        env:
          SF_USER: ${{ secrets.SF_USER }}
          SF_PROJECT: ${{ secrets.SF_PROJECT }}
        run: |
          scp -i ~/.ssh/id_ed25519 out/hello.txt $SF_USER@frs.sourceforge.net:/home/frs/project/$SF_PROJECT/FlameOS-BETA/
