# .github/workflows/main.yml
name: Upload Mirror
on: [workflow_dispatch]

jobs:
  upload-to-nextcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Archive files
        run: |
          sudo apt-get update
          sudo apt-get install zip wget -y
          mkdir -p out
          wget https://mirror.adectra.com/archlinux/iso/2025.09.01/archlinux-2025.09.01-x86_64.iso -O archlinux-2025.09.01-x86_64.iso 
          ./.github/scripts/upload-mirror.sh archlinux-2025.09.01-x86_64.iso FlameOS-Beta https://mirror.theflames.fun
